# Generated by Django 4.1.7 on 2023-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechical_assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='alt_mobile',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
