# Generated by Django 4.1.7 on 2023-03-25 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vechical_assist', '0004_mechanic_car_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.BooleanField(default=False)),
                ('Address', models.CharField(max_length=512)),
                ('contact', models.PositiveIntegerField()),
                ('lat', models.IntegerField()),
                ('log', models.IntegerField()),
                ('car_company', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
