# Generated by Django 4.1.7 on 2023-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechical_assist', '0005_service_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='log',
            field=models.FloatField(),
        ),
    ]
