# Generated by Django 4.2 on 2023-04-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle1', '0007_service_request_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='mech_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('mech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle1.mechanic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle1.customer')),
            ],
        ),
    ]
