# Generated by Django 4.2 on 2023-04-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle1', '0008_mech_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
