# Generated by Django 4.2 on 2023-04-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle1', '0009_service_request_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mech_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle1.service_request'),
        ),
    ]
