# Generated by Django 4.2 on 2023-04-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle1', '0010_alter_mech_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mech_request',
            old_name='user',
            new_name='service_request',
        ),
        migrations.AlterField(
            model_name='service_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle1.customer'),
        ),
    ]
